### PR TITLE
updated instagram icon

### PR DESCRIPTION
**Pull request by crowmagnumb**
Updated the instagram icon to be more modern

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks. For the curious,

before: screen shot 2015-06-23 at 20 39 05

after: screen shot 2015-06-23 at 20 39 19

**Comment by crowmagnumb** [comment]
Cheers! Looks good.

**Comment by crowmagnumb** [comment]
On this note, it looks a tiny bit small to me. Is this somehow due to the svg image I uploaded or is something else controlling that? How can that be adjusted?

**Comment by zimbatm** [comment]
You're right, the svg is smaller than it's viewport.

If you open the file in a svg editor you will see that and adjust it. I would do it but my Inkscape is broken at the moment.

Another way to see the problem is to create an test.html file that contains the following:
```
<img src="src/instagram.svg" border=1>
```
If you open this with your browser you will see the space between the icon and the 1 pixel border.

**Comment by zimbatm** [comment]
Here is another view of the issue: https://samcollins.github.io/css-social-buttons/src/

**Comment by crowmagnumb** [comment]
The size issue is another thing altogether but really shouldn't matter
since they are svg's and scale down well. I'm not sure how to scale the
image down. Anyway, I have made a new pull request with an updated icon
that I got from Instagram's own site. The border issue is fixed and it is
the exact icon they are pushing at the moment.

**Comment by zimbatm** [comment]
Cheers !

**Pull request merged**
